filter:
  excluded_paths:
    - 'test/'
    - 'vendor/'

build:
  dependencies:
    override:
      - composer upgrade --no-interaction --prefer-dist
  nodes:
    my-node:
      services:
        mysql: 5.7
    analysis:
      project_setup:
        override: true
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis

tools:
  external_code_coverage:
    timeout: 600 