--- 
before_script: 
  - "composer self-update"
  - "composer install --prefer-source --no-interaction --dev"
language: php
php:
  - 8.0
script: XDEBUG_MODE=coverage ./vendor/bin/phpunit test --coverage-text --coverage-clover=coverage.clover    
after_script: 
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover 